// <auto-generated />
using System;
using EasyNet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Easy.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230522114206_Prima")]
    partial class Prima
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyNet.Models.Commento", b =>
                {
                    b.Property<int>("IdCommento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCommento"));

                    b.Property<int>("FkPost")
                        .HasColumnType("int");

                    b.Property<int?>("FkUtente")
                        .HasColumnType("int");

                    b.Property<string>("Testo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCommento");

                    b.HasIndex("FkPost");

                    b.HasIndex("FkUtente");

                    b.ToTable("Commentos");
                });

            modelBuilder.Entity("EasyNet.Models.Post", b =>
                {
                    b.Property<int>("IdPost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPost"));

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FkUtente")
                        .HasColumnType("int");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPost");

                    b.HasIndex("FkUtente");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("EasyNet.Models.Utente", b =>
                {
                    b.Property<int>("IdUtente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtente"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataNascita")
                        .HasColumnType("datetime2");

                    b.Property<int>("FkPost")
                        .HasColumnType("int");

                    b.Property<string>("FotoProfilo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUtente");

                    b.HasIndex("FkPost");

                    b.ToTable("Utentes");
                });

            modelBuilder.Entity("EasyNet.Models.Commento", b =>
                {
                    b.HasOne("EasyNet.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("FkPost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyNet.Models.Utente", "utente")
                        .WithMany("Commentos")
                        .HasForeignKey("FkUtente");

                    b.Navigation("Post");

                    b.Navigation("utente");
                });

            modelBuilder.Entity("EasyNet.Models.Post", b =>
                {
                    b.HasOne("EasyNet.Models.Utente", "Utente")
                        .WithMany()
                        .HasForeignKey("FkUtente");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("EasyNet.Models.Utente", b =>
                {
                    b.HasOne("EasyNet.Models.Post", "post")
                        .WithMany()
                        .HasForeignKey("FkPost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("post");
                });

            modelBuilder.Entity("EasyNet.Models.Utente", b =>
                {
                    b.Navigation("Commentos");
                });
#pragma warning restore 612, 618
        }
    }
}
